# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "40984690914cf86ab7f00173d8ba487b"
application_url = "https://samba-nodes-tub-affect.trycloudflare.com"
embedded = true
name = "boa-home-task-MO"
handle = "boa-home-task-mo"

[build]
include_config_on_deploy = true
dev_store_url = "home-assignment-223.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://samba-nodes-tub-affect.trycloudflare.com/auth/callback",
  "https://samba-nodes-tub-affect.trycloudflare.com/auth/shopify/callback",
  "https://samba-nodes-tub-affect.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
